name: CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      mane: Checkout 
      uses: actions/checkout@v3

      name: Setup 
      uses: actions/setup-dotnet@v2
    
      name: Test
      run: dotnet test --no-build --verbosity normal
